### ISSUE TITLE
Error in running PipelineModel.py

### ISSUE THREAD

**Issue by methylome** [AdirthaBorgohain/NER-RE#6]
I have found your project is quite interesting for learning NER and RE. I have succeeded in training NER and RE. However I got the following error in running PipelineModel.py

```
python PipelineModel.py
/opt/mambaforge/envs/ner-er/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator TfidfTransformer from version 1.0 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:                                                       
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations                                                                      
  UserWarning,
/opt/mambaforge/envs/ner-er/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 1.0 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:                                                        
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations                                                                      
  UserWarning,
Traceback (most recent call last):
  File "PipelineModel.py", line 58, in <module>
    pipeline = PipelineModel()
  File "PipelineModel.py", line 24, in __init__
    "tokenize", name="re_tok2vec", source=self.__re)
  File "/opt/mambaforge/envs/ner-er/lib/python3.7/site-packages/spacy/language.py", line 778, in add_pipe                                                                
    factory_name, source, name=name
  File "/opt/mambaforge/envs/ner-er/lib/python3.7/site-packages/spacy/language.py", line 713, in create_pipe_from_source                                                 
    opts=", ".join(source.component_names),
KeyError: "[E944] Can't copy pipeline component 'tokenize' from source 'en_pipeline': not found in pipeline. Available components: transformer, relation_extractor"      
```

My environment is as follows:
```
# Name                    Version                   Build  Channel
spacy                     3.2.1            py37h796e4cb_1    conda-forge
spacy-alignments          0.8.6            py37h18700ff_0    conda-forge
spacy-legacy              3.0.12             pyhd8ed1ab_0    conda-forge
spacy-loggers             1.0.4              pyhd8ed1ab_0    conda-forge
spacy-transformers        1.1.4              pyhd8ed1ab_0    conda-forge
(ner-er) [root@octopus ner-re]# conda list
# packages in environment at /opt/mambaforge/envs/ner-er:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
catalogue                 2.0.8            py37h89c1867_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37h43b0acd_1    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py37h89c1867_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cuda-version              11.8                 h70ddcb2_2    conda-forge
cudatoolkit               11.8.0              h37601d7_11    conda-forge
cudnn                     8.8.0.121            h0800d71_1    conda-forge
cupy                      11.2.0           py37h17e6d27_0    conda-forge
cymem                     2.0.7            py37hd23a5d3_0    conda-forge
cython-blis               0.7.8            py37hda87dfa_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
fastrlock                 0.8              py37hd23a5d3_2    conda-forge
filelock                  3.12.0             pyhd8ed1ab_0    conda-forge
fsspec                    2023.1.0           pyhd8ed1ab_0    conda-forge
huggingface_hub           0.15.0             pyhd8ed1ab_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py37h89c1867_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
langcodes                 3.3.0              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge 
libgfortran5              12.2.0              h337968e_19    conda-forge   
libhwloc                  2.9.1           cuda112_haf10fcf_5    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge   
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge 
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libprotobuf               3.21.12              h3eb15da_0    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libxml2                   2.11.4               h0d562d8_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               16.0.4               h4dfa4b3_0    conda-forge
magma                     2.5.4                hc72dce7_4    conda-forge
markupsafe                2.1.1            py37h540881e_1    conda-forge   
mkl                       2022.2.1         h84fe81f_16997    conda-forge
murmurhash                1.0.9            py37hd23a5d3_0    conda-forge
nccl                      2.17.1.1             h0800d71_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge    
ninja                     1.11.1               h924138e_0    conda-forge    
nmslib                    2.1.1            py37h48bf904_1    conda-forge
numpy                     1.21.6           py37h976b520_0    conda-forge
openssl                   3.1.1                hd590300_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    1.3.4            py37he8f5f7f_1    conda-forge
pathy                     0.10.1             pyhd8ed1ab_0    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
preshed                   3.0.8            py37hd23a5d3_0    conda-forge
psutil                    5.9.3            py37h540881e_0    conda-forge
pybind11                  2.10.0           py37h7cecad7_0    conda-forge
pybind11-global           2.10.0           py37h7cecad7_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.8.2            py37h5e8e339_2    conda-forge
pysocks                   1.7.1            py37h89c1867_5    conda-forge
python                    3.7.12          hf930737_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     3_cp37m    conda-forge
pytorch                   1.12.1          cuda112py37h6a44366_201    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py37h540881e_4    conda-forge
readline                  8.2                  h8228510_1    conda-forge
regex                     2022.9.13        py37h540881e_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
sacremoses                0.0.53             pyhd8ed1ab_0    conda-forge
scikit-learn              1.0.2            py37hf9e9bfc_0    conda-forge
scipy                     1.7.3            py37hf2a6cf1_0    conda-forge
setuptools                59.8.0           py37h89c1867_1    conda-forge
shellingham               1.5.1              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
smart_open                5.2.1              pyhd8ed1ab_0    conda-forge
spacy                     3.2.1            py37h796e4cb_1    conda-forge
spacy-alignments          0.8.6            py37h18700ff_0    conda-forge
spacy-legacy              3.0.12             pyhd8ed1ab_0    conda-forge
spacy-loggers             1.0.4              pyhd8ed1ab_0    conda-forge
spacy-transformers        1.1.4              pyhd8ed1ab_0    conda-forge
sqlite                    3.42.0               h2c6b66d_0    conda-forge
srsly                     2.4.5            py37hd23a5d3_0    conda-forge
tbb                       2021.9.0             hf52228f_0    conda-forge
thinc                     8.0.17           py37h48bf904_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tokenizers                0.10.3           py37hcb7a40c_1    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
transformers              4.11.3             pyhd8ed1ab_0    conda-forge
typer                     0.4.2              pyhd8ed1ab_0    conda-forge
typing-extensions         3.10.0.2             hd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
urllib3                   2.0.2              pyhd8ed1ab_0    conda-forge    
wasabi                    0.8.2              pyh44b312d_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge    
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

Thanks in advance.

**Comment by AdirthaBorgohain** [comment]
Hi @methylome ! Glad you're finding the repo useful. For your error, can you check line no, 24 in your`PipelineModel.py` file? 
It should be something like `self.__model.add_pipe("tok2vec", name="re_tok2vec", source=self.__re)`

I believe in place to "tok2vec", it is set to "tokenize" in your file.

**Comment by methylome** [comment]
Sorry, I modified it for resolving the error. The original version ran into the same error.
```
  UserWarning,
Traceback (most recent call last):
  File "PipelineModel.py", line 58, in <module>
    pipeline = PipelineModel()
  File "PipelineModel.py", line 24, in __init__
    "tok2vec", name="re_tok2vec", source=self.__re)
  File "/opt/mambaforge/envs/ner-er/lib/python3.7/site-packages/spacy/language.py", line 778, in add_pipe
    factory_name, source, name=name
  File "/opt/mambaforge/envs/ner-er/lib/python3.7/site-packages/spacy/language.py", line 713, in create_pipe_from_source
    opts=", ".join(source.component_names),
KeyError: "[E944] Can't copy pipeline component 'tok2vec' from source 'en_pipeline': not found in pipeline. Available components: transformer, relation_extractor"
```

**Comment by AdirthaBorgohain** [comment]
Ok understood. You trained the model using transformers right? I notice in my code that it's using tok2vec by default which actually should be dynamic based on how you train the model. I will fix that.

As for resolving your error, change `self.__model.add_pipe("tok2vec", name="re_tok2vec", source=self.__re)` to `self.__model.add_pipe("transformer", name="re_transformer", source=self.__re)`

Let me know if this resolves your issue

**Comment by AdirthaBorgohain** [comment]
Pushed changes to the code. It should hopefully resolve your issue

**Comment by methylome** [comment]
The error was gone, but the result seem wrong.
What I did was:
1) go to NER and run spacy project run all_gpu
2) got to RE and run spacy project run all_gpu
3) run PipelineModel.py

```
python PipelineModel.py 
/opt/mambaforge/envs/ner-er/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator TfidfTransformer from version 1.0 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
/opt/mambaforge/envs/ner-er/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 1.0 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
ℹ Could not determine any instances in doc - returning doc as is.
Text: The up-regulation of RNA was characteristic of an early inducible gene, with maximal upregulation two hours after the addition of BMP-6 and returned to baseline after 24 hours.

Extracted Entities -> [('BMP-6', 'GGP')]

Linked Entities in Knowledge Base ->

Extracted Relations ->
```

**Comment by AdirthaBorgohain** [comment]
If you use the default trained models provided in the codebase, do you face the same issue?

My hunch is that since you're training the models on the provided training data in the code, it's not training that well. The train, dev and val data that is provided here are just sample data and you need a lot more data to make the model perform well.

So, if you actually want to test your own model, I'd recommend collecting a lot more data and retrain the model with that data.

**Comment by methylome** [comment]
After fresh clone, it worked.
```
python PipelineModel.py 
/opt/mambaforge/envs/ner-er/lib/python3.7/site-packages/spacy/util.py:833: UserWarning: [W095] Model 'en_pipeline' (0.0.0) was trained with spaCy v3.1 and may not be 100% compatible with the current version (3.2.1). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
Text: The up-regulation of RNA was characteristic of an early inducible gene, with maximal upregulation two hours after the addition of BMP-6 and returned to baseline after 24 hours.

Extracted Entities -> [('RNA', 'GGP'), ('BMP-6', 'GGP')]

Linked Entities in Knowledge Base ->
Entity: RNA, CUI: C0000137, Name: 15S RNA
Definition: None
TUI(s): T114, T123
Aliases: (total: 1): 
         RNA, 15S

Extracted Relations ->
('BMP-6', 'RNA') --> Predicted Relation: Regulates
```

**Comment by methylome** [comment]
Is prodi only way to generate a train dataset from my data(text)?

**Comment by AdirthaBorgohain** [comment]
Not necessarily. You don't need prodigy at all. But the way I've written the code here, your data needs to be in a specific format (samples are in `assets` directory). Doesn't matter if you use prodigy or any other tool or method as long as the format of your data is the same. 

You can obviously modify how you parse the data as well. In the `scripts` directory for both NER and RE, you'll find a `parse_data.py`. That essentially uses the files from `assets` directory and converts them into .spacy format. 

The .spacy format is necessary and it's structure is fixed. The previous steps as to how you structure the data that way is upto you. 

Hope this helps.

**Comment by methylome** [comment]
Thanks a lot for your prompt response.

**Comment by methylome** [comment]
Could you explain how to generate train, dev, and test datasets compatible to your code not using prodi? What field should be in the datasets or what package would be best for it?

**Comment by AdirthaBorgohain** [comment]
Hi. Sorry for the delay in responding. 
To answer your questions, in order to generate train, dev, and test datasets compatible with my code, for NER data, the necessary fields are `spans` and `text`. Rest is optional. For RE data, you'd need `text`, `tokens`, `spans`, and `relations`.  Ideally, you can use the same data for both RE and NER since RE data already consists of the NER fields in addition to fields it needs on its own.

As for the package, unfortunately, I am not really sure of what to suggest. But any decent annotation too should do the job as long as you are able to extract the necessary fields.
